defmodule SetmyInfo.ElixirModuleLoader do
  @moduledoc """
  Public API for dynamic Elixir module compilation, loading, and memory
  lifecycle management under the `SetmyInfo` namespace.

  ## Core workflow

      # Compile source code — module is immediately loaded, key auto-assigned
      {:ok, key, _module} = SetmyInfo.ElixirModuleLoader.compile(source)

      # Compile a file
      {:ok, key, module} = SetmyInfo.ElixirModuleLoader.compile_file("plugins/plugin.ex")

      # Compile only (no load/register) — useful for a build phase
      {:ok, [{module, binary}]} = SetmyInfo.ElixirModuleLoader.compile(source, load: false)

      # Load under a caller-provided UUID (deferred-load pattern).
      # The caller does NOT call module.known_fun/1 directly — function names
      # come from external systems and are discovered at runtime:
      uuid = SetmyInfo.ElixirModuleLoader.generate_uuid()
      {:ok, module} = SetmyInfo.ElixirModuleLoader.load_source(uuid, source)
      {:ok, module} = SetmyInfo.ElixirModuleLoader.load_file(uuid, "plugins/plugin.ex")

      # Load an already-compiled module by its atom name
      {:ok, key, module} = SetmyInfo.ElixirModuleLoader.load_by_name(MyApp.Plugin)

      # Reload a registered module by key (restores code if previously released)
      {:ok, module} = SetmyInfo.ElixirModuleLoader.load(key)

      # Discover what functions the module exports at runtime
      {:ok, exports} = SetmyInfo.ElixirModuleLoader.functions(key)
      #=> {:ok, [add: 2, multiply: 2]}

      # Capture a function by name (from external system) as a runtime closure
      {:ok, fun} = SetmyInfo.ElixirModuleLoader.get_function(key, "mask_first_name", 1)
      masked = fun.(["Alice"])    # → "A****"

      # Caller decides when to release — frees working-set slot and code memory
      :ok = SetmyInfo.ElixirModuleLoader.release(key)

  ## Keys

  Every registered module is addressed by a 128-bit key auto-generated by
  `compile/1`, `compile_file/1`, and `load_by_name/1`. Keys can also be
  created manually with `generate_key/0` or `generate_uuid/0`.

  Any key-taking function accepts either of two interchangeable forms:

  * a **16-byte binary** — `<<_::128>>` (from `generate_key/0`)
  * a **UUID string** — `"550e8400-e29b-41d4-a716-446655440000"` (from `generate_uuid/0`)

  Use `key_to_uuid/1` to convert a binary key to its UUID string form for
  external storage. Use `generate_uuid/0` to create a key in UUID form from
  the start.

  ## No imposed interface

  The library does not require loadable modules to implement any callbacks,
  expose specific function names, or follow any naming convention. Function
  names are not known at compile time — they come from external systems.
  Discover them at runtime with `functions/1` and capture them via `get_function/3`:

      {:ok, exports} = SetmyInfo.ElixirModuleLoader.functions(key)
      {:ok, fun}     = SetmyInfo.ElixirModuleLoader.get_function(key, fn_name, 1)
      result         = fun.([arg])

  ## Memory lifecycle

  Modules registered via `compile/1` or `compile_file/1` have their BEAM
  code managed by the library: `release/1` purges the code from the VM when
  no other loaded key uses the same module. A subsequent `load/1` restores it
  transparently from the stored binary or by recompiling the source file.

  Modules loaded with `load_by_name/1` are not purged on release — the
  library does not own externally-compiled code.

  ## Invalid keys

  Every key-taking function raises `ArgumentError` when given a binary that
  is neither a 16-byte key nor a well-formed UUID string.
  """

  alias SetmyInfo.ElixirModuleLoader.{
    Compiler,
    Loader,
    Registry,
    UUID
  }

  @typedoc "A 16-byte binary module key."
  @type key :: <<_::128>>

  @typedoc "A canonical UUID string, e.g. `\"550e8400-e29b-41d4-a716-446655440000\"`."
  @type uuid :: String.t()

  @typedoc "Either accepted key form — a 16-byte binary or a UUID string."
  @type key_or_uuid :: key() | uuid()

  # ── Key management ───────────────────────────────────────────────────────────

  @doc "Generate a cryptographically-random 128-bit binary key."
  @spec generate_key() :: key()
  def generate_key, do: :crypto.strong_rand_bytes(16)

  @doc "Generate a random version-4 UUID string."
  @spec generate_uuid() :: uuid()
  def generate_uuid, do: UUID.generate()

  @doc "Convert a 128-bit binary key to its UUID string form."
  @spec key_to_uuid(key()) :: uuid()
  def key_to_uuid(<<_::128>> = key), do: UUID.from_key(key)

  # ── Compilation ─────────────────────────────────────────────────────────────

  @doc """
  Compile an Elixir source string and optionally load and register the result.

  When `load: true` (the default), the primary module is loaded into the VM,
  registered under an auto-generated 128-bit key, and the module is
  immediately usable. The BEAM binary is stored so the code can be restored
  automatically after `release/1` purges it.

      {:ok, key, module} = compile(source)
      result = module.my_fun(args)

  When `load: false`, the source is compiled and the `[{module, binary}]`
  list is returned without any registry entry being created. The modules are
  loaded into the VM as a side effect of compilation, but are not tracked
  by the library and cannot be addressed by key or UUID.

      {:ok, [{module, binary}]} = compile(source, load: false)

  This is useful for a build/pre-compile phase: compile many sources, inspect
  or persist the BEAM binaries, and defer registration until the module is
  actually needed (using `load_source/2` or `load_file/2`).

  For a source string that defines several modules, only the primary (first
  compiled) module is registered and returned when `load: true`; all defined
  modules are always loaded into the VM.
  """
  @spec compile(String.t(), keyword()) ::
          {:ok, key(), module()} | {:ok, [{module(), binary()}]} | {:error, term()}
  def compile(source, opts \\ []) when is_binary(source) do
    if Keyword.get(opts, :load, true) do
      with {:ok, [{module, beam} | _]} <- Compiler.from_source(source) do
        key = generate_key()
        :ok = Registry.register(key, module, %{beam_source: {:binary, beam}})
        with {:ok, ^module} <- Loader.load(key), do: {:ok, key, module}
      end
    else
      Compiler.from_source(source)
    end
  end

  @doc """
  Compile an Elixir `.ex` file (or load a pre-compiled `.beam` file) and
  optionally load and register the result.

  When `load: true` (the default), the primary module is loaded into the VM
  and registered under an auto-generated key. For `.ex` files the source path
  is remembered so the module can be recompiled from disk after `release/1`
  purges the code.

      {:ok, key, module} = compile_file("plugins/plugin.ex")

  When `load: false` (only valid for `.ex` files), the file is compiled and
  `{:ok, [{module, binary}]}` is returned without creating a registry entry.
  Passing `load: false` for a `.beam` path returns `{:error, :load_required_for_beam}`.

  Returns `{:ok, key, module}` when `load: true` and `{:ok, [{module, binary}]}`
  when `load: false`.
  """
  @spec compile_file(Path.t(), keyword()) ::
          {:ok, key(), module()} | {:ok, [{module(), binary()}]} | {:error, term()}
  def compile_file(path, opts \\ []) when is_binary(path) do
    load? = Keyword.get(opts, :load, true)

    cond do
      not load? and String.ends_with?(path, ".beam") ->
        {:error, :load_required_for_beam}

      not load? ->
        Compiler.from_file(path)

      String.ends_with?(path, ".beam") ->
        key = generate_key()

        with {:ok, module} <- Compiler.from_beam_file(path) do
          :ok = Registry.register(key, module, %{beam_source: {:file, path}})

          with {:ok, ^module} <- Loader.load(key), do: {:ok, key, module}
        end

      true ->
        key = generate_key()

        with {:ok, [{module, _beam} | _]} <- Compiler.from_file(path) do
          :ok = Registry.register(key, module, %{beam_source: {:ex_file, path}})

          with {:ok, ^module} <- Loader.load(key), do: {:ok, key, module}
        end
    end
  end

  # ── Loading ──────────────────────────────────────────────────────────────────

  @doc """
  Load an already-compiled module by its atom name, register it under a new
  auto-generated key, and return `{:ok, key, module}`.

  The module must be loadable from the VM code path (present in the
  application's compiled output or a dependency). The library does not manage
  the code memory for modules loaded this way — `release/1` removes the key
  from the working set but does not purge the module's code.

  Returns `{:error, reason}` when `:code.ensure_loaded/1` fails (module not
  found on the code path).
  """
  @spec load_by_name(module()) :: {:ok, key(), module()} | {:error, term()}
  def load_by_name(module_name) when is_atom(module_name) do
    case :code.ensure_loaded(module_name) do
      {:module, ^module_name} ->
        key = generate_key()
        :ok = Registry.register(key, module_name)
        with {:ok, ^module_name} <- Loader.load(key), do: {:ok, key, module_name}

      {:error, reason} ->
        {:error, reason}
    end
  end

  @doc """
  Register a pre-compiled BEAM binary under `key_or_uuid` and load it into
  the working set, returning `{:ok, module}` — without recompiling.

  `module` and `binary` are the values from a `compile/2` call with
  `load: false`. This is the efficient path when source code is compiled once
  (build phase) and loaded on demand many times:

      # Build phase — compile source ONCE
      {:ok, [{module, binary}]} = EML.compile(source, load: false)

      # Persist `binary` to disk or an in-memory cache if needed

      # Request phase — load without recompiling
      uuid = EML.generate_uuid()
      {:ok, ^module} = EML.load_binary(uuid, module, binary)

      {:ok, fun} = EML.get_function(uuid, fn_name, 1)
      result = fun.([data])

      :ok = EML.release(uuid)

  If the module is already in the VM from an earlier compile call, the
  Loader skips reloading it. If the VM slot was freed by a previous release,
  it is restored from the stored binary — the caller holds no responsibility
  for that lifecycle.
  """
  @spec load_binary(key_or_uuid(), module(), binary()) :: {:ok, module()} | {:error, term()}
  def load_binary(key_or_uuid, module_name, beam_binary)
      when is_atom(module_name) and is_binary(beam_binary) do
    key = normalize(key_or_uuid)
    :ok = Registry.register(key, module_name, %{beam_source: {:binary, beam_binary}})
    with {:ok, ^module_name} <- Loader.load(key), do: {:ok, module_name}
  end

  @doc """
  Compile an Elixir source string, register it under the caller-provided
  `key_or_uuid`, load it into the working set, and return `{:ok, module}`.

  Unlike `compile/1`, the caller controls the key — enabling patterns where
  UUID-keyed modules are lazily loaded per request and released after use.

  Function names are not known at compile time; the caller discovers them at
  runtime and invokes them by name:

      uuid = SetmyInfo.ElixirModuleLoader.generate_uuid()
      {:ok, module}  = SetmyInfo.ElixirModuleLoader.load_source(uuid, source)
      {:ok, exports} = SetmyInfo.ElixirModuleLoader.functions(uuid)
      # exports => [{:mask, 1}, ...]
      {:ok, fun}     = SetmyInfo.ElixirModuleLoader.get_function(uuid, :mask, 1)
      masked         = fun.(["sensitive-value"])
      :ok            = SetmyInfo.ElixirModuleLoader.release(uuid)

  The BEAM binary is stored so `release/1` + `load/1` transparently restores
  the code without recompiling.
  """
  @spec load_source(key_or_uuid(), String.t()) :: {:ok, module()} | {:error, term()}
  def load_source(key_or_uuid, source) when is_binary(source) do
    key = normalize(key_or_uuid)

    with {:ok, [{module, beam} | _]} <- Compiler.from_source(source) do
      :ok = Registry.register(key, module, %{beam_source: {:binary, beam}})
      with {:ok, ^module} <- Loader.load(key), do: {:ok, module}
    end
  end

  @doc """
  Compile an Elixir `.ex` file (or load a `.beam` file), register it under
  the caller-provided `key_or_uuid`, load it into the working set, and return
  `{:ok, module}`.

  Like `load_source/2` but sources from a file. The path is stored so the
  library can restore the code automatically after `release/1` purges it.

  Function names come from external systems and are not known at compile time.
  Use `functions/1` to discover them and `get_function/3` to capture them:

      uuid = SetmyInfo.ElixirModuleLoader.generate_uuid()
      {:ok, _module} = SetmyInfo.ElixirModuleLoader.load_file(uuid, "maskers/name.ex")
      {:ok, fun}     = SetmyInfo.ElixirModuleLoader.get_function(uuid, fn_name_from_config, 1)
      masked         = fun.([value])
      :ok            = SetmyInfo.ElixirModuleLoader.release(uuid)
  """
  @spec load_file(key_or_uuid(), Path.t()) :: {:ok, module()} | {:error, term()}
  def load_file(key_or_uuid, path) when is_binary(path) do
    key = normalize(key_or_uuid)

    result =
      if String.ends_with?(path, ".beam") do
        with {:ok, module} <- Compiler.from_beam_file(path) do
          :ok = Registry.register(key, module, %{beam_source: {:file, path}})
          {:ok, module}
        end
      else
        with {:ok, [{module, _beam} | _]} <- Compiler.from_file(path) do
          :ok = Registry.register(key, module, %{beam_source: {:ex_file, path}})
          {:ok, module}
        end
      end

    with {:ok, module} <- result,
         {:ok, ^module} <- Loader.load(key) do
      {:ok, module}
    end
  end

  @doc """
  Load the module registered under `key_or_uuid` and return the module atom.

  If the module's code was purged by an earlier `release/1`, it is restored
  first from the registered source (recompiles `.ex`, reloads `.beam` or
  in-memory binary). Idempotent — loading an already-loaded key returns the
  same module.
  """
  @spec load(key_or_uuid()) :: {:ok, module()} | {:error, term()}
  def load(key_or_uuid), do: Loader.load(normalize(key_or_uuid))

  # ── Release ──────────────────────────────────────────────────────────────────

  @doc """
  Release the module loaded under `key_or_uuid`.

  Removes the key from the loaded working set. When the module's code is
  library-managed (compiled via `compile/1` or `compile_file/1`) and no other
  loaded key uses the same module, the code is also deleted and soft-purged
  from the VM, freeing memory. The registration is kept — a subsequent
  `load/1` restores the code automatically.

  Returns `{:error, :not_loaded}` if the key is not in the loaded working set.
  """
  @spec release(key_or_uuid()) :: :ok | {:error, :not_loaded}
  def release(key_or_uuid), do: Loader.release(normalize(key_or_uuid))

  @doc "True if `key_or_uuid` is currently in the loaded working set."
  @spec loaded?(key_or_uuid()) :: boolean()
  def loaded?(key_or_uuid), do: Loader.loaded?(normalize(key_or_uuid))

  # ── Function discovery ───────────────────────────────────────────────────────

  @doc """
  List the public functions exported by the module registered under
  `key_or_uuid`, as `[{name, arity}]`.

  Loads the key on demand (restoring code if needed). Callers that do not
  know the module in advance can discover its full interface at runtime:

      {:ok, exports} = SetmyInfo.ElixirModuleLoader.functions(key)
      #=> {:ok, [mask_first_name: 1, mask_last_name: 1]}
  """
  @spec functions(key_or_uuid()) :: {:ok, [{atom(), non_neg_integer()}]} | {:error, term()}
  def functions(key_or_uuid) do
    key = normalize(key_or_uuid)

    with {:ok, module} <- Loader.load(key) do
      {:ok, exported_functions(module)}
    end
  end

  @doc """
  Capture a specific function from the module registered under `key_or_uuid`
  and return it as a closure that accepts a **list** of arguments.

  `name` may be an atom or a string — function names received from external
  systems (databases, config, HTTP requests) arrive as strings and are
  accepted directly without manual conversion.

  This is the correct pattern when the caller does not know function names at
  compile time:

      # Caller discovers available function names at runtime
      {:ok, exports} = SetmyInfo.ElixirModuleLoader.functions(uuid)
      #=> {:ok, [mask_first_name: 1, mask_last_name: 1]}

      # Function name arrives from an external system
      fn_name = "mask_first_name"   # from config / DB / HTTP param

      {:ok, fun} = SetmyInfo.ElixirModuleLoader.get_function(uuid, fn_name, 1)
      masked = fun.(["Alice"])       # → "A****"

      # Compose at runtime — caller builds the pipeline
      masking_pipeline = fn person ->
        {:ok, mask_fn} = SetmyInfo.ElixirModuleLoader.get_function(uuid, fn_name, 1)
        mask_fn.([person.first_name])
      end

  The closure captures the module atom; it remains valid for the lifetime of
  the loaded key. After `release/1` the closure may return unexpected results
  if the code is purged — callers should acquire and use the function within
  a single load/release lifecycle.

  Returns `{:error, :not_found}` when no function with `name/arity` is
  exported. Returns `{:error, term}` when the module cannot be loaded.
  """
  @spec get_function(key_or_uuid(), atom() | String.t(), non_neg_integer()) ::
          {:ok, ([term()] -> term())} | {:error, term()}
  def get_function(key_or_uuid, name, arity) when is_integer(arity) and arity >= 0 do
    with {:ok, name_atom} <- coerce_to_atom(name),
         key = normalize(key_or_uuid),
         {:ok, module} <- Loader.load(key) do
      if {name_atom, arity} in exported_functions(module) do
        {:ok, fn args when is_list(args) -> apply(module, name_atom, args) end}
      else
        {:error, :not_found}
      end
    end
  end

  # ── Private ───────────────────────────────────────────────────────────────────

  defp coerce_to_atom(name) when is_atom(name), do: {:ok, name}

  defp coerce_to_atom(name) when is_binary(name) do
    try do
      {:ok, String.to_existing_atom(name)}
    rescue
      ArgumentError -> {:error, :not_found}
    end
  end

  defp exported_functions(module) do
    if function_exported?(module, :__info__, 1) do
      module.__info__(:functions)
    else
      for {f, a} <- module.module_info(:exports), f != :module_info, do: {f, a}
    end
  end

  defp normalize(<<_::128>> = key), do: key
  defp normalize(uuid) when is_binary(uuid), do: UUID.to_key!(uuid)
end
